In [1]:
import pandas as pd
import numpy as np

In [2]:
#Load the csv dataset
insdata= pd.read_csv("train.csv")

In [3]:
insdata.head()

,id,target,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
0,7,0,2,2,5,1,0,0,1,0,...,9,1,5,8,0,1,1,0,0,1
1,9,0,1,1,7,0,0,0,0,1,...,3,1,1,9,0,1,1,0,1,0
2,13,0,5,4,9,1,0,0,0,1,...,4,2,7,7,0,1,1,0,1,0
3,16,0,0,1,2,0,0,1,0,0,...,2,2,4,9,0,0,0,0,0,0
4,17,0,0,2,0,1,0,1,0,0,...,3,1,1,3,0,0,0,1,1,0

In [4]:
insdata.tail()

,id,target,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
595207,1488013,0,3,1,10,0,0,0,0,0,...,4,1,9,6,0,1,1,0,1,1
595208,1488016,0,5,1,3,0,0,0,0,0,...,4,1,3,8,1,0,1,0,1,1
595209,1488017,0,1,1,10,0,0,1,0,0,...,3,2,2,6,0,0,1,0,0,0
595210,1488021,0,5,2,3,1,0,0,0,1,...,4,1,4,2,0,1,1,1,0,0
595211,1488027,0,0,1,8,0,0,1,0,0,...,4,4,3,8,0,1,0,0,0,0

In [5]:
insdata.isnull().sum()

id                0
target            0
ps_ind_01         0
ps_ind_02_cat     0
ps_ind_03         0
ps_ind_04_cat     0
ps_ind_05_cat     0
ps_ind_06_bin     0
ps_ind_07_bin     0
ps_ind_08_bin     0
ps_ind_09_bin     0
ps_ind_10_bin     0
ps_ind_11_bin     0
ps_ind_12_bin     0
ps_ind_13_bin     0
ps_ind_14         0
ps_ind_15         0
ps_ind_16_bin     0
ps_ind_17_bin     0
ps_ind_18_bin     0
ps_reg_01         0
ps_reg_02         0
ps_reg_03         0
ps_car_01_cat     0
ps_car_02_cat     0
ps_car_03_cat     0
ps_car_04_cat     0
ps_car_05_cat     0
ps_car_06_cat     0
ps_car_07_cat     0
ps_car_08_cat     0
ps_car_09_cat     0
ps_car_10_cat     0
ps_car_11_cat     0
ps_car_11         0
ps_car_12         0
ps_car_13         0
ps_car_14         0
ps_car_15         0
ps_calc_01        0
ps_calc_02        0
ps_calc_03        0
ps_calc_04        0
ps_calc_05        0
ps_calc_06        0
ps_calc_07        0
ps_calc_08        0
ps_calc_09        0
ps_calc_10        0
ps_calc_11        0
ps_calc_12        0
ps_calc_13        0
ps_calc_14        0
ps_calc_15_bin    0
ps_calc_16_bin    0
ps_calc_17_bin    0
ps_calc_18_bin    0
ps_calc_19_bin    0
ps_calc_20_bin    0
dtype: int64

In [6]:
insdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 595212 entries, 0 to 595211
Data columns (total 59 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id              595212 non-null  int64
 1   target          595212 non-null  int64
 2   ps_ind_01       595212 non-null  int64
 3   ps_ind_02_cat   595212 non-null  int64
 4   ps_ind_03       595212 non-null  int64
 5   ps_ind_04_cat   595212 non-null  int64
 6   ps_ind_05_cat   595212 non-null  int64
 7   ps_ind_06_bin   595212 non-null  int64
 8   ps_ind_07_bin   595212 non-null  int64
 9   ps_ind_08_bin   595212 non-null  int64
 10  ps_ind_09_bin   595212 non-null  int64
 11  ps_ind_10_bin   595212 non-null  int64
 12  ps_ind_11_bin   595212 non-null  int64
 13  ps_ind_12_bin   595212 non-null  int64
 14  ps_ind_13_bin   595212 non-null  int64
 15  ps_ind_14       595212 non-null  int64
 16  ps_ind_15       595212 non-null  int64
 17  ps_ind_16_bin   595212 non-null  int64
 18  ps_ind_17_bin   595212 non-null  int64
 19  ps_ind_18_bin   595212 non-null  int64
 20  ps_reg_01       595212 non-null  float64
 21  ps_reg_02       595212 non-null  float64
 22  ps_reg_03       595212 non-null  float64
 23  ps_car_01_cat   595212 non-null  int64
 24  ps_car_02_cat   595212 non-null  int64
 25  ps_car_03_cat   595212 non-null  int64
 26  ps_car_04_cat   595212 non-null  int64
 27  ps_car_05_cat   595212 non-null  int64
 28  ps_car_06_cat   595212 non-null  int64
 29  ps_car_07_cat   595212 non-null  int64
 30  ps_car_08_cat   595212 non-null  int64
 31  ps_car_09_cat   595212 non-null  int64
 32  ps_car_10_cat   595212 non-null  int64
 33  ps_car_11_cat   595212 non-null  int64
 34  ps_car_11       595212 non-null  int64
 35  ps_car_12       595212 non-null  float64
 36  ps_car_13       595212 non-null  float64
 37  ps_car_14       595212 non-null  float64
 38  ps_car_15       595212 non-null  float64
 39  ps_calc_01      595212 non-null  float64
 40  ps_calc_02      595212 non-null  float64
 41  ps_calc_03      595212 non-null  float64
 42  ps_calc_04      595212 non-null  int64
 43  ps_calc_05      595212 non-null  int64
 44  ps_calc_06      595212 non-null  int64
 45  ps_calc_07      595212 non-null  int64
 46  ps_calc_08      595212 non-null  int64
 47  ps_calc_09      595212 non-null  int64
 48  ps_calc_10      595212 non-null  int64
 49  ps_calc_11      595212 non-null  int64
 50  ps_calc_12      595212 non-null  int64
 51  ps_calc_13      595212 non-null  int64
 52  ps_calc_14      595212 non-null  int64
 53  ps_calc_15_bin  595212 non-null  int64
 54  ps_calc_16_bin  595212 non-null  int64
 55  ps_calc_17_bin  595212 non-null  int64
 56  ps_calc_18_bin  595212 non-null  int64
 57  ps_calc_19_bin  595212 non-null  int64
 58  ps_calc_20_bin  595212 non-null  int64
dtypes: float64(10), int64(49)
memory usage: 267.9 MB

import xgboost as xgb
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import roc_auc_score, accuracy_score

# Split the data
X = insdata.drop('target', axis=1)
y = insdata['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier

# Initialize models
logistic_regression = LogisticRegression()
random_forest = RandomForestClassifier()
gradient_boosting = GradientBoostingClassifier()
neural_network = MLPClassifier()

models = {
    "Logistic Regression": logistic_regression,
    "Random Forest": random_forest,
    "Gradient Boosting": gradient_boosting,
    "Neural Network": neural_network
}

In [7]:
from sklearn.model_selection import train_test_split
# Split the data
X = insdata.drop('target', axis=1)
y = insdata['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [8]:

from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

# Define the models
models = {
    "Support Vector Machine": SVC(probability=True),  # probability=True for ROC AUC score
    "Neural Network": MLPClassifier(max_iter=1000),
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Random Forest": RandomForestClassifier(),
    "Gradient Boosting": XGBClassifier(use_label_encoder=False, eval_metric='logloss')
}

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
# Train and evaluate each model
for name, model in models.items():
    # Train the model
    model.fit(X_train, y_train)

    # Predictions
    y_pred = model.predict(X_test)
    y_pred_proba = model.predict_proba(X_test)[:, 1]  # Probability estimates for ROC AUC score
    
    # Evaluation
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    roc_auc = roc_auc_score(y_test, y_pred_proba)
    
    print(f"Model: {name}")
    print(f"Accuracy: {accuracy}")
    print(f"Precision: {precision}")
    print(f"Recall: {recall}")
    print(f"F1 Score: {f1}")
    print(f"ROC AUC Score: {roc_auc}")
    print("\n")